---
- name: Ensure PostgreSQL user exists
  community.postgresql.postgresql_user:
    name: "{{ odoo_db_user }}"
    password: "{{ odoo_db_password }}"
    role_attr_flags: CREATEDB
    state: present
  become: true
  become_user: postgres
