#!/usr/bin/env bash
# ==========================================
# Module: 14-security-jails.sh
# Configure Fail2ban jails for SSH and Nginx
# ==========================================

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"

source "${BASE_DIR}/lib/logger.sh"
source "${BASE_DIR}/lib/functions.sh"
source "${BASE_DIR}/config/installer.conf"

if [[ "${FAIL2BAN_ENABLE}" != "yes" ]]; then
    info "Fail2ban is disabled, skipping jail configuration"
    exit 0
fi

info "Configuring Fail2ban jails"

# Create jail.local with configured parameters
cat > /etc/fail2ban/jail.local <<EOF
# ==========================================
# Vina Business Server - Fail2ban Jails
# Generated by installer
# ==========================================

[DEFAULT]
bantime  = ${FAIL2BAN_BANTIME}
findtime = ${FAIL2BAN_FINDTIME}
maxretry = ${FAIL2BAN_MAXRETRY}

[sshd]
enabled = true
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s

[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log

[nginx-bad-request]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/access.log
maxretry = 10
EOF

# Validate configuration before applying
info "Validating Fail2ban configuration"
if fail2ban-client --test > /dev/null 2>&1; then
    success "Fail2ban configuration is valid"
else
    error "Fail2ban configuration validation failed"
    fail2ban-client --test
    exit 1
fi

# Restart service to apply changes
systemctl restart fail2ban

# Verify service is running
if systemctl is-active --quiet fail2ban; then
    success "Fail2ban jails configured successfully"
    info "Active jails:"
    fail2ban-client status | grep "Jail list" || true
else
    error "Fail2ban service failed to start"
    journalctl -u fail2ban --no-pager -n 20
    exit 1
fi
