oca_dir: /opt/odoo/oca
oca_odoo_branch: "19.0"
oca_repositories:
  - server-tools
  - web
  - partner-contact
  - reporting-engine
  - helpdesk
  - field-service
  - contract
  - account-financial-tools
  - account-financial-reporting
  - account-reconcile
  - account-invoicing
  - stock-logistics-workflow
  - stock-logistics-reporting
  - stock-logistics-warehouse
  - product-attribute
  - sale-workflow
  - sale-reporting
  - crm
  - hr
  - hr-expense
  - hr-timesheet
  - project
