[backend]
i-srv-1 ansible_host=<IP_ADDRESS> ansible_user=mmshj ansible_become=yes

[frontend]
i-srv-2 ansible_host=<IP_ADDRESS> ansible_user=mmshj ansible_become=yes

[all:vars]
ansible_python_interpreter=/usr/bin/python3
