---
- name: Skip SSL setup if disabled
  meta: end_play
  when: not ssl_enable
- name: Skip SSL setup if disabled
  meta: end_play
  when: not ssl_enable


- name: Install SSL packages
  apt:
    name:
      - openssl
      - python3-cryptography
    state: present


- name: Ensure SSL directory exists
  file:
    path: "{{ ssl_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"


# ==========================
# Internal CA
# ==========================

- name: Generate internal CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_dir }}/vina-ca.key"
    size: 4096


- name: Generate internal CA certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_dir }}/vina-ca.crt"
    privatekey_path: "{{ ssl_dir }}/vina-ca.key"
    provider: selfsigned
    selfsigned_not_after: "+3650d"


# ==========================
# Server Certificate
# ==========================


- name: Generate backend private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_dir }}/{{ odoo_ssl_name }}.key"
    size: 2048


- name: Generate backend CSR
  community.crypto.openssl_csr:
    path: "{{ ssl_dir }}/{{ odoo_ssl_name }}.csr"
    privatekey_path: "{{ ssl_dir }}/{{ odoo_ssl_name }}.key"
    country_name: "{{ ssl_country }}"
    organization_name: "Vina Group"
    common_name: "{{ odoo_backend_ip }}"
    subject_alt_name:
      - "IP:{{ odoo_backend_ip }}"
      - "DNS:{{ odoo_backend_hostname }}"

- name: Sign backend certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_dir }}/{{ odoo_ssl_name }}.crt"
    csr_path: "{{ ssl_dir }}/{{ odoo_ssl_name }}.csr"
    provider: ownca
    ownca_path: "{{ ssl_dir }}/vina-ca.crt"
    ownca_privatekey_path: "{{ ssl_dir }}/vina-ca.key"
    ownca_not_after: "+825d"


- name: Secure SSL private keys
  file:
    path: "{{ item }}"
    mode: "0600"
  loop:
    - "{{ ssl_dir }}/vina-ca.key"
    - "{{ ssl_dir }}/{{ odoo_ssl_name }}.key"



# ==========================
# Nginx SSL
# ==========================


- name: Deploy nginx SSL config
  template:
    src: odoo-ssl.conf.j2
    dest: /etc/nginx/sites-available/odoo
  notify:
    - reload nginx


- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/odoo
    dest: /etc/nginx/sites-enabled/odoo
    state: link
    force: yes


- name: Validate nginx
  command:
    nginx -t
  changed_when: false
