---
- name: Pause for manual standard Odoo database creation
  ansible.builtin.pause:
    prompt: |
      ============================================================
      نصب پایه Oودو تمام شد.

      لطفاً در مرورگر این آدرس را باز کنید:
        https://{{ odoo_backend_ip }}

      در صفحه wizard اودو، دیتابیس را به صورت استاندارد بسازید.

      بعد از ساخت موفق دیتابیس، به ترمینال برگردید و Enter بزنید.
      ============================================================
