---
- name: Create Odoo runtime directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
  loop:
    - "{{ odoo_home }}/data"
    - "{{ odoo_home }}/logs"
    - "{{ odoo_custom_addons }}"
    - "{{ oca_dir }}"
    - "{{ odoo_conf_dir }}"   # /etc/odoo

- name: Determine worker count based on CPU cores
  ansible.builtin.set_fact:
    odoo_workers: "{{ (ansible_processor_vcpus * 2 + 1) if ansible_processor_vcpus >= 2 else 0 }}"
    odoo_max_cron_threads: "{{ 2 if ansible_processor_vcpus >= 2 else 1 }}"

- name: Deploy odoo.env
  ansible.builtin.copy:
    dest: "{{ odoo_conf_dir }}/odoo.env"
    content: "ODOO_DB_USER=odoo\n"
    owner: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
    mode: "0640"

- name: Deploy odoo.conf from template
  ansible.builtin.template:
    src: odoo.conf.j2
    dest: "{{ odoo_conf_dir }}/odoo.conf"
    owner: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
    mode: "0640"
  notify: restart odoo
