---
- name: Create odoo system group
  ansible.builtin.group:
    name: "{{ odoo_group }}"
    system: true
    state: present

- name: Create odoo system user
  ansible.builtin.user:
    name: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
    system: true
    create_home: true
    home: "{{ odoo_home }}"
    shell: /bin/bash
    comment: "Odoo system user"
    state: present

- name: Ensure odoo home directory permissions
  ansible.builtin.file:
    path: "{{ odoo_home }}"
    owner: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
    mode: '0755'
    state: directory

- name: Create required Odoo directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ odoo_user }}"
    group: "{{ odoo_group }}"
    mode: '0755'
    state: directory
  loop:
    - "{{ odoo_home }}/custom_addons"
    - "{{ odoo_home }}/logs"
    - "{{ odoo_home }}/backups"
    - "{{ odoo_home }}/filestore"
